#!/usr/bin/env bash

set -e
set -x

## Upgrades all global pip packages, for Python 3

for pip_pkg in $(sudo -H pip3 list --outdated | sed '1,2d' | cut -d' ' -f1); do
    if [ "$pip_pkg" = 'PyYAML' ]; then
        continue
    fi
    sudo -H pip3 install -U "$pip_pkg"
done
